### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by tiagomacarios** [bast/hdf5-cmake-example#1]
Ubuntu - latest
Cmake 2.8 and 3.2 - same result

root@7895c41efb5c:~/hdf5-cmake-example-master# cmake CMakeLists.txt
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS)
CMake Error at CMakeLists.txt:46 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "writedata.x".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.

-- Configuring incomplete, errors occurred!

**Comment by bast** [comment]
Sorry for that. This is indeed an error in `CMakeLists.txt` - will fix it shortly.
Please note that the recommended way to build a CMake project is out-of-source:

```
mkdir build
cd build
cmake ..
make
```

(but this is independent of this problem)
